version: "3.8"
name: hw11
services:
  pg:
    image: postgres
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"
    env_file:
      - ./.env

  code :
    build: ./
    image: lexxai/web_hw11:latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - pg

